### ISSUE TITLE
FR: Adapt to the Home Assistant theme instead of using custom themes

### ISSUE THREAD

**Issue by rasssta** [tmjo/charger-card#5] opened 2021-04-25 09:32 UTC
(Might be related to #1...)

Instead of using "hard coded" themes explicitly for this card I would like this card to be able to adapt to the standard/current Home Assistant theme.

It does not look particularly nice with my current theme. Especially the rounded vs. non-rounded edges.

I *could* manually set the theme colors to the same as my HASS theme. But as I've never ran into this issue with any other card I would assume that it's possible to make this happen automatically?

Some screenshots:

![image](https://user-images.githubusercontent.com/4455235/115988016-fef50200-a5b7-11eb-90ed-e04e9d32be63.png)
![image](https://user-images.githubusercontent.com/4455235/115988051-28ae2900-a5b8-11eb-928c-18827b7fec34.png)
![image](https://user-images.githubusercontent.com/4455235/115988063-3499eb00-a5b8-11eb-827c-a6dfdfe266bb.png)
![image](https://user-images.githubusercontent.com/4455235/115988078-51362300-a5b8-11eb-9efe-5ef8880e1921.png)

**Comment by rasssta** [comment] 2021-04-25 09:37
In compact mode, text is not aligned properly.

![image](https://user-images.githubusercontent.com/4455235/115988523-788def80-a5ba-11eb-8ece-7e5734505139.png)

**Comment by tmjo** [comment] 2021-04-26 05:52
Hi and thanks for commenting! I see your point and will take a look, but haven't had too much time for such improvements lately. Do you have any idea where to start or know how, feel free to contribute with a PR too! Thx.

**Comment by tmjo** [comment] 2021-05-01 21:58
Hi @rasssta, do you mind sharing which theme you are using? I've never used themes, but I can give it a try and see if it is easy to fix.

**Comment by rasssta** [comment] 2021-05-01 22:02
I'm using ios-dark-mode-blue-red from https://github.com/basnijholt/lovelace-ios-themes, installed via HACS :)

**Comment by tmjo** [comment] 2021-05-01 22:09
Cool. I guess this looks a little better just by removing the hardcoded theme thingy:

![image](https://user-images.githubusercontent.com/54450177/116796112-4dcff980-aada-11eb-9871-bb131c998cbb.png)

Still missing the rounded corners though, I'll check for that. It is probably hardcoded somehow too. This card look-and-feel is heavily forked from the [vacuum-card](https://github.com/denysdovhan/vacuum-card) and I see that one have the same issue too. I'm not an UI expert, but I'll take a look and see if there is something I can do easily.

**Comment by rasssta** [comment] 2021-05-01 22:15
I use xiaomi-vacuum-card (not sure if that's the same) without any issues. Though, with some vertical stack combos.

![image](https://user-images.githubusercontent.com/4455235/116796224-2cbbd880-aadb-11eb-8cbc-bc946c1959da.png)

**Comment by tmjo** [comment] 2021-05-01 22:44
No, it is a different card. Would this be what you expect to see with your theme?

![image](https://user-images.githubusercontent.com/54450177/116796779-8c1be780-aadf-11eb-882e-1d8b4805f3f7.png)

**Comment by rasssta** [comment] 2021-05-01 22:46
Yes!

**Comment by tmjo** [comment] 2021-05-01 22:50
Great! I'll just verify that it still looks ok for the other variants and do a release. I should probably remove the whole custom theme thingy integrated into the card, but for now I've just added an option to select "theme_custom" in the card config. Make sure you select it once you upgrade :)

![image](https://user-images.githubusercontent.com/54450177/116796874-40b60900-aae0-11eb-9312-ebee8a2f6628.png)

Thanks for the feedback!

**Comment by rasssta** [comment] 2021-05-01 23:00
Might want to call it theme_default instead, makes more sense imo :-)

**Comment by tmjo** [comment] 2021-05-01 23:46
Here we go! Please test v0.0.9, hopefully it should fix the themes issues and do some bug fix on compact view. Let me know what you think, and kindly close the issue if it solves the issue. Thanks!

**Comment by tmjo** [comment] 2021-05-01 23:54
> Might want to call it theme_default instead, makes more sense imo :-)

I kindof agree with you here, in fact I did that first, but then chose to give it a "new" name for backwards compatibility. For some reason, selecting this the "theme_custom" without any theme applied, makes the card look transparent with black text. Not sure why, maybe that is the reason why the vacuum-card was made this way in the first place. So to avoid any issues for people using it "default", I opted for this way for now.

**Comment by rasssta** [comment] 2021-05-02 07:06
Thanks. Works great! :)

**Comment by rasssta** [comment] 2021-05-02 07:31
I was a bit too quick there... ;) 

I found out that it looks odd when I add this card to a lovelace view that is configured to use panel mode.

With everything expanded, it looks good:
![image](https://user-images.githubusercontent.com/4455235/116805696-60711f80-ab28-11eb-8cde-cb0fad5ad432.png)

But if I then decrease it, it looks odd:
![image](https://user-images.githubusercontent.com/4455235/116805718-90202780-ab28-11eb-8df2-aea26d07c5a1.png)

Also, the compact view looks odd (in non-panel mode) when hiding the name:
![image](https://user-images.githubusercontent.com/4455235/116805793-0b81d900-ab29-11eb-8121-981f69dc6227.png)

But if I show the name it looks fine.

**Comment by rasssta** [comment] 2021-05-02 07:32
Compact view in panel mode:
![image](https://user-images.githubusercontent.com/4455235/116805842-5d2a6380-ab29-11eb-8a1a-4d7260655598.png)

**Comment by tmjo** [comment] 2021-05-02 11:53
Yeah, my css skills are not water proof. Released v0.0.10 now that seems to fix it on my views, please have a look. There are still css bugs here and there, but I think it is better now.

**Comment by rasssta** [comment] 2021-05-02 12:19
Same issue. I think it has something to do with height=100% or similar. Because it fills out that column in the grid until it reaches the bottom of the browser window.

**Comment by rasssta** [comment] 2021-05-02 12:27
Full screen:
![image](https://user-images.githubusercontent.com/4455235/116813101-6da30400-ab52-11eb-86f9-421e1461e793.png)

And if I decrease the height of the window:
![image](https://user-images.githubusercontent.com/4455235/116813116-814e6a80-ab52-11eb-9ef2-51c845807064.png)

**Comment by tmjo** [comment] 2021-05-03 05:58
Hmm, doesn't appear on my side. Are you sure you properly cleared cache when trying the new version? Here's my normal view of full and compact:
![image](https://user-images.githubusercontent.com/54450177/116845077-231e9780-abe5-11eb-9d36-1d8ac71df340.png)

And panel view:
![image](https://user-images.githubusercontent.com/54450177/116845100-329de080-abe5-11eb-9aad-8c1abe5a1439.png)

panel compact:
![image](https://user-images.githubusercontent.com/54450177/116845127-43e6ed00-abe5-11eb-9acf-0e266aec49ad.png)

**Comment by rasssta** [comment] 2021-05-06 10:20
Yeap, cache cleaned. I did a workaround and included it into a vertical stack, works fine that way.

**Closed** 2021-05-06 10:20 UTC

**Comment by tmjo** [comment] 2021-05-06 14:07
Aha, yes, I see that I had a vertical stack also in Panel mode since I copied the code from my normal view. I'll see if I can reproduce it without vertical stack and see if it can be easily fixed, but I'll wait for a rainy day to do it :)

Thanks for the feedbacks!
